name: Deploy To Netlify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.8'
          cache: 'yarn'
            
      - name: Setup Environment
        run: make install
        
      - name: Build and Zip the Game
        run: make release-web

      - name: Deploy to netlify
        run: make netlify-deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}